version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "topic-test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  listener:
    build: "./listener"
    container_name: listener
    environment:
      BROKER_URL: ${HOST_IP}:9092
      INFURA_API_KEY: c11683b6f8994117bd89eb49666ceaeb
      INFURA_WS_URL: wss://mainnet.infura.io/ws/v3
      SAMPLE_CONTRACT_ADDRESS: 0x3845badAde8e6dFF049820680d1F14bD3903a5d0
      SAMPLE_CONTRACT_ABI: ./sample/abi/etherSandABI.json

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
  indexer:
    build: "./indexer"
    container_name: indexer
    environment:
      BROKER_URL: ${HOST_IP}:9092
      SAMPLE_CONTRACT_ADDRESS: 0x3845badAde8e6dFF049820680d1F14bD3903a5d0
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: etherSand
